### PR TITLE
Use Element as type param

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by renatocaval** [comment]
@seglo, you suggested that on chat. Here it is!

**Comment by renatocaval** [comment]
I have a second thought about it. Maybe we should standardize on `Envelope` to reinforce the idea that its something holding a payload and an offset (and possibly other things).

**Comment by ignasi35** [comment]
+1 to `Envelope` instead of `Element` (and element variants)

**Comment by renatocaval** [comment]
Closing in favor of #58

**Pull request closed without merging**
