### PR TITLE
Java formatter

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by patriknw** [comment]
more specifically, this should be reformatted after https://github.com/akka/akka-projection/pull/249 has been merged

**Comment by renatocaval** [comment]
@patriknw, this is one is rebased after merging #249

**Comment by patriknw** [comment]
ok, can be merged after successful validation

**Comment by renatocaval** [comment]
This one has some serious merge conflicts mistakes. They are now all fixed. I will merge as soon as Travis finishes.

**Pull request merged**
