### PR TITLE
use patience from ScalaTestWithActorTestKit

### PR DESCRIPTION
**Pull request by patriknw**
* at least until we see that there is a problem
* default is 3 seconds, with 100 ms interval

### CODE REVIEW

**Comment by renatocaval** [comment]
there is a problem
https://travis-ci.com/github/akka/akka-projection/jobs/328638121#L345

**Comment by patriknw** [comment]
yeah, I realized that the long patience was for test containers startup. Changed that to not use futureValue for that wait.

also made it possible to run without test containers, with local Cassandra instance: `sbt -Ddisable-cassandra-testcontainer=true`

**Comment by seglo** [comment]
The testcontainer for Cassandra is started later than the `docker-compose` container was in the earlier version of the tests.  That's why the first test catches the timeout.

In Alpakka Kafka we use `TestKitBase.remainingOrDefault` to avoid the proliferation of various timeout intervals throughout the tests.  This gives us one simple configuration `akka.test.single-expect-default` that can be tuned for the whole testsuite.

**Comment by patriknw** [comment]
That init timeout must be much longer than ordinary assert timeouts (30 s vs 3 s). We don't want to use 30 s for all timeouts.

**Pull request merged**
