### PR TITLE
Akka 2.7 dependency

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by octonato** [comment]
```scala
[error] Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.11.4 requires Jackson Databind version >= 2.11.0 and < 2.12.0
[error] 	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error] 	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error] 	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error] 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:853)
```

Failing because of jackson version in the scala module. 
Looks like it's being pulled transitively?

**Comment by octonato** [comment]
Well, it seems that `akka-serialization-jackson` is pulling it.

```scala
[info]   +-com.typesafe.akka:akka-serialization-jackson_2.13:2.7.0-M1 [S]
....
[info]   | |
[info]   | +-com.fasterxml.jackson.module:jackson-module-scala_2.13:2.11.4 [S]
```

**Comment by patriknw** [comment]
ok, let's stay at Jackson 2.11.4 here until we have an Akka milestone with the update.

**Comment by patriknw** [comment]
It became a mess with the Jackson dependency anyway so I released Akka 2.7.0-M2 and this is now using that.

**Pull request merged**
