### PR TITLE
fix: DynamoDB evict offsets per slice

### PR DESCRIPTION
**Pull request by patriknw**
* don't use evicted state when saving changed timestamp per slice
* evict time window for each slice
* remove keep-number-of-entries and evict-interval

### CODE REVIEW

**Comment by patriknw** [comment]
@leviramsey please review this

**Review by leviramsey — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
some samples failed, but that is unrelated and fixed in https://github.com/akka/akka-projection/pull/1248

**Comment by leviramsey** [comment]
Refs: https://github.com/akka/akka-persistence-dynamodb/issues/95

**Pull request merged**
