### PR TITLE
warn about too many tags for Cassandra

### PR DESCRIPTION
**Pull request by patriknw**
I can add a similar warning in APC reference docs too.

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM, and yes note on APC docs also good.

**Comment by octonato** [comment]
merge conflict fixed

**Review by seglo — APPROVED** [review]
LGTM, but it might be more appropriate to put this warning in the Akka Persistence Cassandra plugin docs upstream, if it's not there already.

**Comment by patriknw** [comment]
> it might be more appropriate to put this warning in the Akka Persistence Cassandra plugin docs upstream

It's need at both places because users don't read (all) documentation.
Corresponding warning in APC docs https://github.com/akka/akka-persistence-cassandra/pull/837

**Pull request merged**
