### PR TITLE
Let Slick offset store use plain SQL

### PR DESCRIPTION
**Pull request by octonato**
This an experiment, not to be merged (at least not for now)

References #405 

Slick adds double quotes to all table and column names when querying or in inserting/updating statements. This can be annoying for Postgres users. Postgres treats the names as case sensitive when wrapped in double quotes.

In this experiment, we workaround the double quotes limitation by not relying on Slick to generate statements. Instead we use plain SQL queries. Slick is only used for the connection/thread management. 

Moreover, the 'OFFSET' column is problematic for Postgres since 'offset' is a keyword in Postgres. Alternatively, we could rename it to CURRENT_OFFSET. 

Since we are about to cut release 1.0, we don't want to bring such a major change right now. 

I'm putting out this PR (as draft) so we can discuss how to proceed. 

We could eventually rename the OFFSET column to CURRENT_OFFSET before the release, but using plain SQL queries may be too impactful to be added just before releasing.

### CODE REVIEW

**Comment by renatocaval** [comment]
Btw, there is not way to escape OFFSET. So a renaming is needed if we want it to be case insensitive.

**Comment by renatocaval** [comment]
Hmm, I think there is nothing we can do here, to be honest. 

With release 1.0, we will have Postgres users using a case sensitive schema definition. That means that even if we move to plain SQL we will need to always wrap the table and column names with double quotes. Meaning that we will need to use case sensitive statements forever. 

To get out of this I only see two options:

* change it now, but is risky
* move to plain SQL later and force existing Postgres users to run alter table statements to rename the table and the columns

I don't think the added value justifies it.

**Comment by patriknw** [comment]
Renaming the column to `CURRENT_OFFSET` seems like low effort and low risk so we can do that before 1.0.0.

Regarding the Slick and JDBC compatibility I have a new thought. We want to facilitate migration especially from Slick to JDBC because we want to phase out Slick eventually. We don't care about migration in the other direction. What if we make the default statements for JDBC nice and clean (without quotes), but add a compatibility config flag `slick-compat=on`, which can be enabled by users that are migrating from Slick?

If I understand it right, that would be a small change in Dialect.scala. Adding another SlickPostgresDialect there if that config flag is set.

**Comment by renatocaval** [comment]
I agree with the compat mode. 

That said, changing the offset column now makes sense because if we remove the quotes on a future release, users using a DB other than Postgres won't be impacted at all.

I will PR the column name change.

**Comment by renatocaval** [comment]
btw, we don't even need a slick-compat flag, it's enough if we add a new dialect called "slick-postgres".

**Comment by patriknw** [comment]
> it's enough if we add a new dialect called "slick-postgres"

great!

**Comment by octonato** [comment]
superseded by #622

**Pull request closed without merging**
