### PR TITLE
Pre release 24.10

### PR DESCRIPTION
**Pull request by sebastian-alfers**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by sebastian-alfers** [comment]
Depends on akka-persistence-r2dbc

**Comment by sebastian-alfers** [comment]
Something is off with gh actions:
```
Run git fetch origin pull/1235/merge:scratch
fatal: couldn't find remote ref pull/123[5](https://github.com/akka/akka-projection/actions/runs/11517794110/job/32063223715?pr=1235#step:3:6)/merge
Error: Process completed with exit code 128.
```

**Comment by sebastian-alfers** [comment]
@johanandren Do you see anything I am doing wrong here re the failing actions?

**Comment by johanandren** [comment]
Weird, have never seen that git error before in github.

**Comment by johanandren** [comment]
Maybe just try drop this PR and open a new one from the same branch?

**Comment by johanandren** [comment]
Or push the branch to this repo and open a PR from it here

**Comment by sebastian-alfers** [comment]
Another try in https://github.com/akka/akka-projection/pull/1236

**Pull request closed without merging**
