### PR TITLE
MiMa configuration

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, does this automatically use the same directory conventions for mima filter files as in akka/akka?

**Comment by renatocaval** [comment]
> LGTM, does this automatically use the same directory conventions for mima filter files as in akka/akka?

That's what I was referring to recommended configuration. 

I don't know how this is done. I need to dig it, but want to get the minimal config out.

**Comment by patriknw** [comment]
ok, I would find it convenient if we used the same conventions in different projects (maybe that is by default?)

**Review by seglo — APPROVED** [review]
LGTM

**Pull request merged**
