### PR TITLE
Update Cassandra plugin to 1.0.2

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by patriknw** [comment]
@renatocaval New APC works but 
```
[error] /home/travis/build/akka/akka-projection/akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala:52:3: exception during macro expansion: 
314[error] java.util.MissingResourceException: Can't find bundle for base name org.scalactic.ScalacticBundle, locale en_US
```

**Comment by patriknw** [comment]
Strange, it's only for jdk8 but not jdk11. I'll rerun

**Comment by patriknw** [comment]
All good in second run. Nondeterministic macros? 🎲

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by renatocaval** [comment]
which macros are there?

**Comment by patriknw** [comment]
the error message was about: exception during macro expansion ... scalactic

**Pull request merged**
