### PR TITLE
use Envelope as type param

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by renatocaval** [comment]
Like #56, but using `Envelope` instead.

**Comment by seglo** [comment]
I think `Element`, `StreamElement`, or `Event` might be more clear that we're doing with entries from some data source, but I guess it's rather subjective.  What do others think? @ignasi35 @patriknw @ennru

**Comment by ignasi35** [comment]
> I think `Element`, `StreamElement`, or `Event` might be more clear that we're doing with entries from some data source, but I guess it's rather subjective. What do others think? @ignasi35 @patriknw @ennru

Brain dumping my first impression on each alternative.

- `Element` is `Thing`, `Stuff`. I think is my least-preferred option.
- `StreamElement... same.
- `Event` is a bit overloaded, plus the item traversing is _not just_ the Event. I think  `Envelope` resonates with me, but probably because of Akka Persistence Query's `EventEnvelope`.

**Comment by ignasi35** [comment]
`Envelope` has the advantage that's generic enough to allow for more metadata to be added later. Meaning, at the moment, we only require an `Event` and an `Offset` in the `Envelope` but we may want to require some other metadata later (enqueueing timestamp, aka event creation TS).

**Comment by patriknw** [comment]
I vote for Envelope, over Element, because it's a bit more specific to the domain we have here. It's telling that it wraps the element/message/event and includes some meta data.

**Comment by renatocaval** [comment]
Ok, let's move in that direction then. I will fix the merge conflict and close the other one.

**Comment by patriknw** [comment]
maybe do the full search-replace after merging Cassandra PR

**Comment by renatocaval** [comment]
Changed everywhere except on a few comments here and there were we are talking either about the elements of a tuple or the elements of a stream in a generic way.

**Pull request merged**
