### PR TITLE
Sort import and remove grouping

### PR DESCRIPTION
**Pull request by renatocaval**
Applied using IntelliJ with this settings:

Screenshot 2020-04-24 at 15 56 45

for the record: 

Preferences > Editor > Code Style > Scala

On right panel in "Imports" tab. 

Seems to be only available in IntelliJ, not in scalafmt.

### CODE REVIEW

**Comment by patriknw** [comment]
Good, that is what I use. I also have Import Layout (but maybe that is default):
```
java
_______ blank line _______
scala
_______ blank line _______
all other imports
_______ blank line _______
```

**Comment by patriknw** [comment]
no, different layout. Can we use the one I proposed?

**Comment by patriknw** [comment]
For the record, we have an PR in Akka for sorting imports from sbt https://github.com/akka/akka/pull/28780

**Comment by renatocaval** [comment]
Applied suggested layout

**Pull request merged**
