### PR TITLE
bump: Akka gRPC 2.4.4, Akka 2.9.6

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM once compiler is happy

**Comment by patriknw** [comment]
compiler warning comes from akka-grpc: https://github.com/akka/akka-grpc/pull/1992

**Comment by johanandren** [comment]
Best would be if we can disable fatal warnings for all Akka gRPC generated sources, since this project is not in control of them.

**Comment by patriknw** [comment]
ok, I'll try to disable that here

**Review by johanandren — APPROVED** [review]

**Pull request merged**
